version: "3.8"

services:
  api:
    build: ./apps/api
    ports:
      - "5000:5000"

  ai:
    build: ./apps/ai
    ports:
      - "8000:8000"

  web:
    build: ./apps/web
    ports:
      - "3000:3000"
